Bootstrap: docker
From: continuumio/miniconda3:latest
Stage: condabuild
%files
environments/nanopore/environment.yml /environment.yml
environments/extras.yml /extras.yml

%labels
authors="Matt Bull" 
description="Docker image containing all requirements for the ARTIC project's ncov2019 pipeline"

%post
/opt/conda/bin/conda install mamba -c conda-forge && \
/opt/conda/bin/mamba env create -f /environment.yml #&& \
#/opt/conda/bin/mamba env update -f /extras.yml -n artic

Bootstrap: docker
From: debian:buster-slim
Stage: final

%post
apt-get update
apt-get install -y git procps
apt-get install -y software-properties-common
sed -i "/^# deb.*universe/ s/^# //" /etc/apt/sources.list
apt-get update
apt-get install -y python3 \
  python3-pip \
  zlib1g-dev \
  libbz2-dev \
  liblzma-dev
# install fieldbioinformatics v1.3.0-dev
pip3 install git+https://github.com/artic-network/fieldbioinformatics@1.3.0-dev
apt-get clean -y

%runscript
exec "artic" "$@"

