Bootstrap: docker
From: continuumio/miniconda3:latest
Stage: condabuild
%files
environments/nanopore/environment.yml /environment.yml
environments/extras.yml /extras.yml

%labels
authors="Matt Bull" 
description="Docker image containing all requirements for the ARTIC project's ncov2019 pipeline"

%post
/opt/conda/bin/conda install mamba -c conda-forge && \
/opt/conda/bin/mamba env create -f /environment.yml && \
/opt/conda/bin/mamba env update -f /extras.yml -n artic

Bootstrap: docker
From: debian:buster-slim
Stage: final

%setup
mkdir ${SINGULARITY_ROOTFS}/extra_software

%post
apt-get update
apt-get install -y git procps
apt-get install -y software-properties-common
sed -i "/^# deb.*universe/ s/^# //" /etc/apt/sources.list
apt-get update
apt-get install -y python3 \
  python3-pip \
  zlib1g-dev \
  libbz2-dev \
  liblzma-dev \
  wget \
  libz-dev \
  libcurl4-openssl-dev \
  libncurses5-dev \
  libffi-dev \
  bzip2 \
  g++ \
  gcc \
  libssl-dev \
  curl \
  make \
  cmake \
  python-virtualenv \
  python3-venv \
  libboost-all-dev
cd ${SINGULARITY_ROOTFS}/extra_software
# install fieldbioinformatics v1.3.0-dev
pip3 install git+https://github.com/artic-network/fieldbioinformatics@1.3.0-dev
apt-get clean -y
# install biopython
git clone https://github.com/biopython/biopython
cd biopython
python3 setup.py build
python3 setup.py install
cd ..
pip3 install biopython
# install git lfs
wget https://github.com/git-lfs/git-lfs/releases/download/v3.1.4/git-lfs-linux-amd64-v3.1.4.tar.gz
tar xfvz git-lfs-linux-amd64-v3.1.4.tar.gz
bash install.sh
# install medaka
git clone https://github.com/nanoporetech/medaka.git
cd medaka
make install
cd ..
# install htslib
wget https://github.com/samtools/htslib/releases/download/1.12/htslib-1.12.tar.bz2
tar -vxjf htslib-1.12.tar.bz2
cd htslib-1.12
make
cd ..
# install artic-tools
export PATH=${SINGULARITY_ROOTFS}/extra_software/htslib-1.12:$PATH
git clone --recursive https://github.com/will-rowe/artic-tools.git
mkdir artic-tools/build
cd artic-tools/build
cmake ..
make -j4
cd ../..
# install muscle
wget https://drive5.com/muscle/downloads3.8.31/muscle3.8.31_i86linux32.tar.gz 
tar xf muscle3.8.31_i86linux32.tar.gz
mv muscle3.8.31_i86linux32 muscle
# install samtools
#wget https://github.com/samtools/samtools/releases/download/1.12/samtools-1.12.tar.bz2
#tar -vxjf samtools-1.12.tar.bz2
#mv samtools-1.12 samtools && cd samtools
#./configure
#make
#cd ..
# install minimap2
#git clone https://github.com/lh3/minimap2
#cd minimap2
#make
#cd ..

%environment
export PATH=${SINGULARITY_ROOTFS}/extra_software/minimap2:$PATH
export PATH=${SINGULARITY_ROOTFS}/extra_software/samtools:$PATH
export PATH=${SINGULARITY_ROOTFS}/extra_software/medaka:$PATH
export PATH=${SINGULARITY_ROOTFS}/extra_software/htslib-1.12:$PATH
export PATH=/opt/conda/envs/artic/bin:$PATH
export PATH=${SINGULARITY_ROOTFS}/extra_software/medaka/venv/bin:$PATH
export PATH=${SINGULARITY_ROOTFS}/extra_software/artic-tools/bin:$PATH
export PATH=${SINGULARITY_ROOTFS}/extra_software:$PATH
export PATH=${SINGULARITY_ROOTFS}/extra_software/biopython:$PATH

%runscript
. activate artic
exec "artic" "$@"
